### ISSUE TITLE
Conversion string to base16

### ISSUE THREAD

**Issue by lucas1** [orestesleal/base64#1]
I'm trying encode name 'Lívia', but return '4CC3AD766961', if I decode this value return 'LÃ­via'.
You know why this problem?
Thanks.

**Comment by lucas1** [comment]
Your decode work good, I tested some sites and return '4ced766961', see:
https://codebeautify.org/string-hex-converter
and
https://codebeautify.org/hex-string-converter

**Comment by orestesleal** [comment]
lucas, it has been fixed, thanks for reporting the issue.

**Comment by orestesleal** [comment]
> Your decode work good, I tested some sites and return '4ced766961', see:
> https://codebeautify.org/string-hex-converter
> and
> https://codebeautify.org/hex-string-converter

Lucas, bom Dia meu amigo!

As you can check this issue was fixed by me a few days ago. I wanted to add a note about the encoding on that site.

That site seems to encode/decode correctly on the surface but, it doesn't show you all the hex characters encoded, which can be misleading, we want to see all the hex chars.

If I use ``b16enc.c`` to encode ``Lívia`` (``echo 'Lívia' >/tmp/input; ./b16enc /tmp/input /tmp/output; cat /tmp/output: 4CC3AD7669610A``). And if I decode the output file (using ``b16dec.c`` ``./b16dec /tmp/output /tmp/out; cat /tmp/out: Lívia`` ). It can be observed that I get the same input.

This is tricky because ``í`` (the 2nd character) gets encoded in ``UTF-8`` (two bytes) to ``0xc3 0xad``) in the file, but the rest of the characters are classic ``ASCII`` encodings so they are one byte each. The site doesn't show you all the UTF-8 bytes, that is the reason I say it can be misleading.

   ``U+00ED | í | 0xc3 0xad | LATIN SMALL LETTER I WITH ACUTE`` as per https://www.utf8-chartable.de/unicode-utf8-table.pl

As can be seen above ``U+00ED`` is the ``UTF-8`` codepoint (which is encoded in the output from the site:  4c``ed``766961). The site encoded the ``UTF-8`` character into the codepoint not the ``UTF-8 HEX`` characters. This explain the differences in encodings (apart from the the previous incorrect handling on my code). So yes, both encodings are correct but are displaying the ``UTF-8`` bytes in different ways (``codepoint vs hex`` representation). 

My ``b16dec`` decode routine was not handling correctly bytes greater than ``0x7F`` (normally ``UTF-8`` encoded characters). Being ``0x7F`` or less, in the classic ``ASCII`` table, which use ``1 byte`` of storage). I've corrected this to support ``UTF-8`` encoding and now the ``b16_dec`` decoding routine works correctly. thanks.

Tenha um bom dia!

Orestes

**Comment by lucas1** [comment]
Hi, good morning.

I understand your detailed explanation.
Thank you for that.
